version: '3.7'

services:
  api:
    build: 
      context: ./
      args: 
        CI: ENABLED
    entrypoint: bash run.sh
    restart: unless-stopped
    volumes:
    - api-volume:/fyle-partner-dashboard-api
    ports:
    - 8006:8006
    depends_on:
    - db
    environment: 
      SECRET_KEY: thisisthedjangosecretkey
      ALLOWED_HOSTS: "*"
      DEBUG: "False"
      API_URL: http://localhost:8006/api
      DATABASE_URL: postgres://postgres:postgres@db:5432/partner_dashboard_db
      DB_HOST: db
      FYLE_BASE_URL: https://lolo.fyle.tech
      FYLE_CLIENT_ID: dummy
      FYLE_CLIENT_SECRET: dummy
      FYLE_REFRESH_TOKEN: dummy
      FYLE_TOKEN_URI: https://lolo.fyle.tech
  db:
    image: "postgres:15"
    environment: 
      POSTGRES_DB: dummy
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./tests/sql_fixtures/reset_db_fixtures/reset_db.sql:/docker-entrypoint-initdb.d/reset_db.sql

volumes:
  api-volume:
