# Generated by Django 3.1.14 on 2022-09-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerorg',
            name='id',
            field=models.AutoField(help_text='Unique Id to identify a partner', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='partnerorg',
            name='name',
            field=models.CharField(help_text='Name of the partner primary org', max_length=255),
        ),
    ]
