# Generated by Django 3.1.14 on 2022-10-04 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0002_auto_20220927_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerorg',
            name='currency',
            field=models.CharField(help_text='Fyle Currency', max_length=5, null=True),
        ),
    ]
