# Generated by Django 4.2.24 on 2025-09-30 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0003_partnerorg_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerorg',
            name='is_org_rebranded',
            field=models.BooleanField(default=False, help_text='Is Org Rebranded'),
        ),
    ]
