# Generated by Django 4.2.25 on 2025-10-27 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0004_partnerorg_is_org_rebranded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerorg',
            name='is_org_rebranded',
            field=models.BooleanField(default=True, help_text='Is Org Rebranded'),
        ),
    ]
